#define IDR_MAINFRAME                   128

#define IDC_EDIT_PATH_LIST                   200001
#define IDC_BUTADDSTART                      200002
#define IDC_BUTFTPEMAIL                      200003
#define IDC_COMBOSTART                       200004
#define IDC_RECORDINGON                      200005
#define IDC_TREE_REFRESH                     200007
#define    IDS_OSD_SPEAKER                                  10000
#define    IDS_ADD_CAM_RESOLUTION                           10001
#define    IDS_ADD_CAM_DATA_ERROR                           10002
#define    IDS_ADD_CAM_CAMERA_NOT_FOUND                     10003
#define    IDS_ADD_CAM_NOT_FOUND                            10004
#define    IDS_ADD_CAM_UNAUTHORIZED                         10005
#define    IDS_SET_RECORDING_ERROR_1                        10006
#define    IDS_SET_RECORDING_ERROR_2                        10007
#define    IDS_ADD_CAM_PROTOCOL                             10008
#define    IDS_ADD_CAM_VIDEO_PORT                           10009
#define    IDS_ADD_CAM_PTZ_DIDO_GROUP                       10010
#define    IDS_ADD_CAM_PTZ                                  10011
#define    IDS_ADD_CAM_DI_1                                 10012
#define    IDS_ADD_CAM_DI_2                                 10013
#define    AFX_IDS_DLG_SETEVENT1                            10014
#define    AFX_IDS_DLG_SETEVENT2                            10015
#define    AFX_IDS_DLG_SETEVENT3                            10016
#define    AFX_IDS_DLG_SETEVENT4                            10017
#define    IDS_SAVE_DATA                                    10018
#define    IDS_OPEN_ODBC_FAIL                               10019
#define    IDS_GROUP_SELECT                                 10020
#define    AFX_IDS_DLG_SETGROUP1                            10021
#define    AFX_IDS_DLG_SETGROUP2                            10022
#define    AFX_IDS_DLG_SETGROUP3                            10023
#define    AFX_IDS_DLG_SETGROUP4                            10024
#define    IDS_DELETE_GROUP1                                10025
#define    IDS_DELETE_GROUP2                                10026
#define    IDS_REMOVE_CAM                                   10027
#define    IDS_EVENT_REACH_MAX                              10028
#define    IDS_EVENT_SAVE                                   10029
#define    IDS_IMPORT_EVENT                                 10030
#define    IDS_LONG_ACTION                                  10031
#define    IDS_CANNOT_CAP_JOYSTICK                          10032
#define    IDS_MAIN_MATRIX                                  10033
#define    IDS_MAIN_SETTINGS                                10034
#define    IDS_MAIN_APPL                                    10035
#define    IDS_LIVEVIEW_GROUP                               10036
#define    IDS_CAM_SELECT                                   10037
#define    IDS_FTP_SERVER                                   10038
#define    IDS_MAX_MONITOR                                  10039
#define    IDS_PATH_TOOLONG                                 10040
#define    IDS_PATH_ROOT                                    10041
#define    IDS_RECORD_TIME_ERROR                            10042
#define    IDS_SELECT_EMAIL                                 10043
#define    IDS_SELECT_SERVER                                10044
#define    IDS_TOOL_ADD_SMTP_SERVER                         10045
#define    IDS_TOOL_DEL_SMTP_SERVER                         10046
#define    IDS_TOOL_MOD_SMTP_SERVER                         10047
#define    IDS_TOOL_ADD_EMAIL_ADDRESS                       10048
#define    IDS_TOOL_DEL_EMAIL_ADDRESS                       10049
#define    IDS_TOOL_MOD_EMAIL_ADDRESS                       10050
#define    IDS_PTZ_DB_ERR                                   10051
#define    IDS_CURL_INI_FAIL                                10052
#define    IDS_CURL_EASY_FAIL                               10053
#define    IDS_SOCKET_LOAD_ERR                              10054
#define    IDS_INI_NOT_FOUND                                10055
#define    IDS_SOCKET_CREATE_ERR                            10056
#define    IDS_INI_ENCP_ERR                                 10057
#define    IDS_TOOL_DEL_REC                                 10058
#define    IDS_TOOL_ADD_REC                                 10059
#define    IDS_TOOL_MOD_REC                                 10060
#define    IDS_TOOL_ADD_GROUP                               10061
#define    IDS_TOOL_DEL_GROUP                               10062
#define    IDS_TOOL_MOD_GROUP                               10063
#define    IDS_TOOL_ADD_EVENT                               10064
#define    IDS_TOOL_DEL_EVENT                               10065
#define    IDS_TOOL_IMPORT_EVENT                            10066
#define    IDS_TOOL_EXPORT_EVENT                            10067
#define    IDS_TOOL_IMPORT_ALL_EVENT                        10068
#define    IDS_TOOL_DEL_STORE_LOC                           10069
#define    IDS_TOOL_ADD_STORE_LOC                           10070
#define    IDS_TOOL_MOD_STORE_LOC                           10071
#define    IDS_TOOL_DEL_FTP                                 10072
#define    IDS_TOOL_ADD_FTP                                 10073
#define    IDS_TOOL_MOD_FTP                                 10074
#define    IDS_CLEAR_EVENT_LIST                             10075
#define    IDS_OSD_TOOLTIP_FIX_RATIO                        10076
#define    IDS_CLEAR_EVENT                                  10077
#define    IDS_OSD_TOOLTIP_SNAPSHOT                         10078
#define    IDS_OSD_TOOLTIP_SEND_AUDIO                       10079
#define    IDS_SELECTBMP                                    10080
#define    IDS_OSD_NO_MIC                                   10081
#define    IDS_SELECTFOLDER                                 10082
#define    IDS_DLG_ADD                                      10083
#define    IDS_SAVE                                         10084
#define    IDS_TREECTRL_REMOVE_CAM1                         10085
#define    IDS_TREECTRL_REMOVE_CAM2                         10086
#define    IDS_SETTINGEVENT                                 10087
#define    IDS_EMAPSETTING                                  10088
#define    IDS_EMAPSAVEAS                                   10089
#define    IDS_DLG_MASS_ASSIGN_IP                           10090
#define    IDS_DLG_SCAN_CAMERA                              10091
#define    IDS_DLG_STREAM_PTZ                               10092
#define    IDS_DLG_CAM_GROUP                                10093
#define    IDS_DLG_CAM_GROUP_NAME                           10094
#define    IDS_DLG_EVENT_SETTING                            10095
#define    IDS_DLG_CAM_SELECTION                            10096
#define    IDS_DLG_ADD_EDIT_FTP                             10097
#define    IDS_DLG_SETTING_RECORDING                        10098
#define    IDS_DLG_SETTING_RECORDING_DUPLICATE              10099
#define    IDS_DLG_ADD_MODIFY_RECORDING                     10100
#define    IDS_DLG_MULTIMONITOR                             10101
#define    IDS_DLG_ADD_EDIT_EMAIL                           10102
#define    IDS_DLG_SETTING_SYSTEM                           10103
#define    IDS_AUTOSCAN_WARNING                             10104
#define    IDS_SELECT_START_TIME                            10105
#define    IDS_ACDEPTADD                                    10106
#define    IDS_ACDEPTMOD                                    10107
#define    IDS_ACDEPTDEL                                    10108
#define    IDS_ACEMPADD                                     10109
#define    IDS_ACEMPMOD                                     10110
#define    IDS_ACEMPDEL                                     10111
#define    IDS_ADD_HOLIDAY                                  10112
#define    IDS_DEL_HOLIDAY                                  10113
#define    IDS_ATTACH_AC                                    10114
#define    IDS_DETACH_AC                                    10115
#define    IDS_AC                                           10116
#define    IDS_ACATTACH                                     10117
#define    IDS_ACDETACH                                     10118
#define    IDS_ADD_CAM_CHANNEL_ID                           10119
#define    IDS_ADD_CAM_ENABLED                              10120
#define    IDS_ADD_CAM_NAME                                 10121
#define    IDS_ADD_CAM_LOADING                              10122
#define    IDS_ADD_CAM_NETWORK_GROUP                        10123
#define    IDS_ADD_CAM_IP                                   10124
#define    IDS_ADD_CAM_CONNECTION_TYPE                      10125
#define    IDS_ADD_CAM_MASK                                 10126
#define    IDS_ADD_CAM_DNS                                  10127
#define    IDS_ADD_CAM_GATEWAY                              10128
#define    IDS_ADD_CAM_PORT                                 10129
#define    IDS_ADD_CAM_MODEL                                10130
#define    IDS_ADD_CAM_MAC                                  10131
#define    IDS_ADD_CAM_CREDENTIALS_GROUP                    10132
#define    IDS_ADD_CAM_USER                                 10133
#define    IDS_ADD_CAM_PASSWORD                             10134
#define    IDS_ADD_CAM_LIVIEW_RECORDING                     10135
#define    IDS_ADD_CAM_LIVEVIEW                             10136
#define    IDS_ADD_CAM_RECORDING                            10137
#define    IDS_ADD_CAM_VIDEO_GROUP                          10138
#define    IDS_ADD_CAM_STREAM                               10139
#define    IDS_ADD_CAM_VIDEO_CMPR_TYPE                      10140
#define    IDS_ADD_CAM_DO                                   10141
#define    IDS_ADD_CAM_PTZ_PROTOCOL                         10142
#define    IDS_ADD_CAM_EVENT_GROUP                          10143
#define    IDS_ADD_CAM_GROUPS_GROUP                         10144
#define    IDS_ADD_CAM_SCAN_CAMS                            10145
#define    IDS_ADD_CAM_GET_CAMS                             10146
#define    IDS_ADD_CAM_MODIFY_VIDEO_PTZ                     10147
#define    IDS_ADD_CAM_EVENT_SETTING                        10148
#define    IDS_ADD_CAM_GROUP_SETTING                        10149
#define    IDS_ADD_CAM_APPLY                                10150
#define    IDS_ADD_CAM_SAVE_DUPLICATE                       10151
#define    IDS_OK                                           10152
#define    IDS_CANCEL                                       10153
#define    IDS_PASSWORD_ERROR                               10154
#define    IDS_CLOSE_PLAYBACK                               10155
#define    IDS_ASSIGN_IP_1                                  10156
#define    IDS_ASSIGN_IP_2                                  10157
#define    IDS_ASSIGN_IP_3                                  10158
#define    IDS_ASSIGN_IP_4                                  10159
#define    IDS_ASSIGN_IP_5                                  10160
#define    IDS_ASSIGN_IP_WARNING                            10161
#define    IDS_ADDACCAM                                     10162
#define    IDS_SETTING_MULTIMONITOR_STARTUP                 10163   
#define    IDS_SETTING_MULTIMONITOR_MAIN                    10164
#define    IDS_INSERT_FAIL_0                                10165
#define    IDS_INSERT_FAIL_1                                10166
#define    IDS_NONE                                         10167
#define    IDS_CLEAR_EVENT_DB                               10168
#define    IDS_HINT_ASSIGN_IP                               10169
#define    IDS_HINT_ADD_CAMERA                              10170
#define    IDS_HINT_GROUP_SETTING                           10171
#define    IDS_HINT_Recording                               10172
#define    IDS_HINT_MONITORS                                10173
#define    IDS_HINT_SYSTEM                                  10174
#define    IDS_HINT_EMAP                                    10175
#define    IDS_HINT_PLAYBACK                                10176
#define    IDS_HINT_CHANGE_LANGUAGE                         10177
#define    IDS_AUTOSCAN                                     10178
#define    IDS_AUTOSCAN_INTERVAL                            10179
#define    IDS_SECOND                                       10180
#define    IDS_SETTING_SYSTEM_RUN                           10181
#define    IDS_LANG_ENGLISH                                 10182
#define    IDS_LANG_GERMAN			                        10183
#define    IDS_LANG_RUSSIAN                                 10184
#define    IDS_LANG_CHINESE_TRAN                            10185
#define    IDS_LANG_CHINESE_SIMP                            10186
#define    IDS_EMAPGROUP                                    10187
#define    IDS_SCAN_TITLES                                  10188
#define    IDS_SCAN_SCAN_BUTTON                             10189
#define    IDS_CAMERA_LIST                                  10190
#define    IDS_GROUP_LIST                                   10191
#define    IDS_CAMERA_GROUP_SETTING_TITLE                   10192
#define    IDS_GROUP_NAME                                   10193
#define    IDS_MODULE                                       10194
#define    IDS_DEFAULT                                      10195
#define    IDS_STATIC_GROUP_PATH                            10196
#define    IDS_GROUP_CAMERA_LIST                            10197
#define    IDS_BTN_SUN                                      10198
#define    IDS_BTN_MON                                      10199
#define    IDS_BTN_TUE                                      10200
#define    IDS_BTN_WED                                      10201
#define    IDS_BTN_THU                                      10202
#define    IDS_BTN_FRI                                      10203
#define    IDS_BTN_SAT                                      10204
#define    IDS_STATIC_REC_TYPE                              10205
#define    IDS_RADIO_CONTINUOUS                             10206
#define    IDS_RADIO_SCHEDULE_EVENT                         10207
#define    IDS_RADIO_SCHEDULING                             10208
#define    IDS_RADIO_EVENT                                  10209
#define    IDS_BUTTON_DUPLICATE                             10210
#define    IDS_PATH_LIST_TITLES                             10211
#define    IDS_GENERAL                                      10212
#define    IDS_HINT_ACCESS_CONTROL                          10213
#define    IDS_CURRENT_RECORDING_PATH                       10214
#define    IDS_EVENTLOG_COLUMN_TITLE                        10215
#define    IDS_EMAPFOLDER                                   10216
#define    IDS_EMAPMAP                                      10217
#define    IDS_EMAPLIVEVIEW                                 10218
#define    IDS_EMAPMOTIONDETECT                             10219
#define    IDS_EMAPCAMERA                                   10220
#define    IDS_EMAPEVENT                                    10221
#define    IDS_EMAPIPCAM                                    10222
#define    IDS_EMAPID                                       10223
#define    IDS_TREECTRL_MODIFY_GROUP                        10224
#define    IDS_TREECTRL_NEW_GROUP                           10225
#define    IDS_TREECTRL_REMOVE_GROUP                        10226
#define    IDS_ADD_NEW_IPCAM                                10227
#define    IDS_FLYAWAY                                      10228
#define    IDS_ADD_INTERNET_IP_CAM                          10229
#define    IDS_MODIFY_IPCAM                                 10230
#define    IDS_REMOVEIPCAM32815                             10231
#define    IDS_IE_EXPLORER                                  10232
#define    IDS_SET_VIDEOSET_FLIP                            10233
#define    IDS_SET_VIDEOSET_UPDISEDOWN                      10234
#define    IDS_SET_FIX_RATIO                                10235
#define    IDS_SNAPSHOT                                     10236
#define    IDS_EXITFULLSCREEN                               10237
#define    IDS_OSD                                          10238
#define    IDS_EMAPTIME                                     10239
#define    IDS_EMAPEVENTTYPE                                10240
#define    IDS_TIME_AFTER                                   10241
#define    IDS_TIMELINE_VIEW                                10242
#define    IDS_PLAYBACK_CONTINUOUS                          10243
#define    IDS_PLAYBACK_EVENT                               10244
#define    IDS_PLAYBACK_STARTTIME                           10245
#define    IDS_PLAYBACK_ENDTIME                             10246
#define    IDS_PLAYBACK_HOST                                10247
#define    IDS_PLAYBACK_TYPE                                10248
#define    IDS_PLAYBACK_FILTER                              10249
#define    IDS_PLAYBACK_NODE_VIEW                           10250
#define    IDS_PLAYBACK_MATRIX                              10251
#define    IDS_PLAYBACK_REFRESH                             10252
#define    IDS_MASS_ASSIGN_HINT                             10253
#define    IDS_PLAYBACK_SPEED                               10254
#define    IDS_MASS_ASSIGN_BTN_RESCAN                       10255
#define    IDS_MASS_ASSIGN_CHANGE_CHECK                     10256
#define    IDS_MASS_ASSIGN_NETWORK_GROUP                    10257
#define    IDS_MASS_ASSIGN_NETWORK_CARD                     10258
#define    IDS_MASS_ASSIGN_IP                               10259
#define    IDS_MASS_ASSIGN_MASK                             10260
#define    IDS_MASS_ASSIGN_GATEWAY                          10261
#define    IDS_MASS_ASSIGN_DNS                              10262
#define    IDS_MASS_ASSIGN_STATUS_HINT                      10263
#define    IDS_MASS_ASSIGN_PREVIOUS                         10264
#define    IDS_MASS_ASSIGN_NEXT                             10265
#define    IDS_MASS_ASSIGN_OK                               10266
#define    IDS_MASS_ASSIGN_LIST_TITLES                      10267
#define    IDS_TRIGGER_TYPE                                 10268
#define    IDS_MASS_ASSIGN_PROCESSING                       10269
#define    IDS_ACDATE                                       10270
#define    IDS_ACSTATUS                                     10271
#define    IDS_ACDEPT                                       10272
#define    IDS_ACNAME                                       10273
#define    IDS_ACLOG                                        10274
#define    IDS_TOOLTIPERROR                                 10275
#define    IDS_ACSET                                        10276
#define    IDS_ACPLAYBACK                                   10277
#define    IDS_ACREPORT                                     10278
#define    IDS_ACREFRESH                                    10279
#define    IDS_SELECT_FOLDER                                10280
#define    IDS_SETTING_SYSTEM_FULLSCREEN                    10281
#define    IDS_TOOL_ADD_ISAP                                10282
#define    IDS_WIZARD_ENABLE                                10283
#define    IDS_WIZARD_SHOW                                  10284
#define    IDS_WIZARD_SETTING                               10285
#define    IDS_WIZARD_NOCAM                                 10286
#define    IDS_WIZARD_P1_1                                  10287
#define    IDS_WIZARD_P1_2                                  10288
#define    IDS_WIZARD_P1_3                                  10289
#define    IDS_WIZARD_P2_1                                  10290
#define    IDS_WIZARD_P3_1                                  10291
#define    IDS_WIZARD_P3_2                                  10292
#define    IDS_WIZARD_P3_3                                  10293
#define    IDS_BASE_TAB_EVENT                               10294
#define    IDS_BASE_TAB_PTZ                                 10295
#define    IDS_BASE_TAB_PRE_POS                             10296
#define    IDS_BASE_TAB_PATROL                              10297
#define    IDS_BASE_TAB_SET_PTZ                             10298
#define    IDS_RECORD_PATH_ERROR		                    10299
#define    IDS_HINT_GATE			                        10300
#define    IDS_ADD_ISAP			                            10301
#define    IDS_AUTOSCAN_SELECT_GROUP	                    10302
#define    IDS_GATE_CONTROL		                            10303
#define    IDS_PLAYBACK_EVENT_TYPE		                    10304
#define    IDS_UNAUTHORIZED		                            10305
#define    IDS_PWD_LENGTH			                        10306
#define    IDS_AUTH_WARNING_1		                        10307
#define    IDS_AUTH_SETTING_TITLE		                    10308
#define    IDS_SCAN_REMOTE_ERROR_1		                    10309
#define    IDS_SCAN_REMOTE_ERROR_2		                    10310
#define    IDS_AUTH_ADD_ERROR_1		                        10311
#define    IDS_AUTH_ADD_ERROR_2		                        10312
#define    IDS_AUTH_ADD_ERROR_3		                        10313
#define    IDS_AUTH_ADD_ERROR_4		                        10314
#define    IDS_DB_INIT_FAIL		                            10315
#define    IDS_AC_TAB_CAM_LIST		                        10316
#define    IDS_AC_TAB_ADD			                        10317
#define    IDS_AC_TAB_DEL			                        10318
#define    IDS_AC_TAB_AC			                        10319
#define    IDS_AC_TAB_ACTIVE		                        10320
#define    IDS_AC_TAB_BRAND		                            10321
#define    IDS_AC_TAB_MODEL		                            10322
#define    IDS_AC_TAB_DEPTADD		                        10323
#define    IDS_AC_TAB_DEPTMOD		                        10324
#define    IDS_AC_TAB_DEPTDEL		                        10325
#define    IDS_AC_TAB_EMPADD		                        10326
#define    IDS_AC_TAB_EMPMOD		                        10327
#define    IDS_AC_TAB_EMPDEL		                        10328
#define    IDS_AC_TAB_REFRESH		                        10329
#define    IDS_AC_TAB_DEPT_EMP		                        10330
#define    IDS_AC_TAB_DEPT			                        10331
#define    IDS_AC_TAB_NAME			                        10332
#define    IDS_AC_TAB_FROM			                        10333
#define    IDS_AC_TAB_TO			                        10334
#define    IDS_AC_TAB_EMP			                        10335
#define    IDS_AC_TAB_ACID			                        10336
#define    IDS_AC_TAB_GATE_PRIVILEGE	                    10337
#define    IDS_AC_TAB_HOLIDAYS		                        10338
#define    IDS_AC_TAB_HOLIDAY_ADD		                    10339
#define    IDS_AC_TAB_HOLIDAY_MOD		                    10340
#define    IDS_AC_TAB_HOLIDAY_DEL		                    10341
#define    IDS_AC_TAB_WEEKEND_OFF		                    10342
#define    IDS_AC_TAB_HOLIDAY		                        10343
#define    IDS_AC_TAB_DATE			                        10344
#define    IDS_AC_TAB_SAME_DATE		                        10345
#define    IDS_ACSETCAM			                            10346
#define    IDS_ACSETDWE			                            10347
#define    IDS_ACSETHOL			                            10348
#define    IDS_ACSETNOTE			                        10349
#define    IDS_GROUP_AUTOSCAN_ENABLE	                    10351
#define    IDS_GROUP_AUTOSCAN_ASK                           10352
#define    IDS_GTSETCHAINADD		                        10353
#define    IDS_GTSETCHAINMOD		                        10354
#define    IDS_GTSETCHAINDEL		                        10355
#define    IDS_GTSETGATEADD		                            10356
#define    IDS_GTSETGATEMOD		                            10357
#define    IDS_GTSETGATEDEL		                            10358
#define    IDS_GTATTACH			                            10359
#define    IDS_GTDETACH			                            10360
#define    IDS_GTSETPLATEADD		                        10361
#define    IDS_GTSETPLATEMOD		                        10362
#define    IDS_GTSETPLATEDEL		                        10363
#define    IDS_GTSEARCH			                            10364
#define    IDS_GTREPORT			                            10365
#define    IDS_GTSET			                            10366
#define    IDS_ACSETCHAIN			                        10367
#define    IDS_ACSETGATEADD		                            10368
#define    IDS_ACSETGATEMOD		                            10369
#define    IDS_ACSETGATEDEL		                            10370
#define    IDS_ACSTTOP			                            10371
#define    IDS_ACSET_WINCAP		                            10372
#define    IDS_ACSET_STATIC		                            10373
#define    IDS_ACSET_STPARKG		                        10374
#define    IDS_ACSET_STGATEINFO		                        10375
#define    IDS_ACSET_STGROUP		                        10376
#define    IDS_ACSET_WARNEMPTY		                        10377
#define    IDS_NOTFUN			                            10378
#define    IDS_HINT_EVENT_TRIGGER_ACTION                    10379
#define    IDS_HINT_LPR                                     10380
#define    IDS_HINT_NAS				                        10381
#define    IDS_TOOL_DEL_NAS			                        10382
#define    IDS_TOOL_ADD_NAS			                        10383
#define    IDS_TOOL_MOD_NAS			                        10384
#define    IDS_NAS_WARNNING			                        10386
#define    IDS_STCAMLIST				                    10388
#define    IDS_STGDETAIL				                    10389
#define    IDS_STGROUPCAM				                    10390
#define    IDS_STDATETIME				                    10391
#define    IDS_STSTATUS				                        10392
#define    IDS_STCDN				                        10393
#define    IDS_CHECKWARN				                    10394
#define    IDS_STGBDETAIL				                    10395
#define    IDS_STGATEINFO				                    10396
#define    IDS_STLP				                            10397
#define    IDS_GTSETCHAIN				                    10398
#define    IDS_GTSETCARD				                    10399

//102-12-12//
#define    IDS_ACSETCHAINADD                                10400
#define    IDS_ACSETCHAINMOD                                10401
#define    IDS_ACSETCHAINDEL                                10402
#define    IDS_GBOXCARDNAME                                 10403                     
#define    IDS_TREECTRL_EXCEPTION_LIVEVIEW                  10404
#define    IDS_TREECTRL_NOT_GROUP                           10405
#define    IDS_TREECTRL_SELECT_GROUP                        10406
#define    IDC_STATIC_GATE_CHAIN				            10407
#define		IDS_OSD_TOOLTIP_RECVIDEO	10408
#define		IDS_SCAN_STATIC					10409
#define		IDS_STCARD                      1050
#define		IDS_STNAME                      1051
#define		IDS_LPLATE                      1052
#define		IDC_LIVE_VIEW                   1053
#define		IDC_DATA_VIEW                   1054
#define		IDC_EMAP_VIEW                   1055
#define		IDC_TOGGLE_IPCAMTREECTRL        1056
#define		IDC_EVENTLIST_VIEW              1057
#define		IDC_OVERVIEW_VIEW               1058
#define		ID_SETIEVIEW                    1059
#define		ID_FULL_SCREEN                  1060
#define		ID_UPGRADE_FIRMWARE             1061
#define		ID_FIRMWARE_UPGRADE             1062
#define		ID_SET_NETWORK                  1063
#define		IDS_PREFIX                      1064
#define		IDS_REGISTSUBFOLDER             1065
#define		IDS_BRAND                       1066
#define		IDS_PRODUCTNAME                 1067
#define		IDS_PLAYBACKNAME                1068
#define		IDS_HEALTH_MONITORNAME          1069
#define		IDR_VERSION2                    1070
#define		IDB_BITMAP_NEW_LOGO             1071
#define		IDB_LOGO                        1072
#define		IDS_RECORD_PATH_ERROR_2         1073
#define		IDS_NORIGHT_CLOSE_SYSTEM           1074
#define		IDC_CHECK_LOGIN_AUTO           1075
#define		IDC_STATIC_CONFIRM              1076
#define		IDC_REMOVE_GROUP              1077
#define		IDC_IPCAM              1078
#define		IDC_MATRIX              1079
#define		IDC_EVENT              1080
#define		IDC_TIME				1081
#define		IDC_CARD				1082
#define		IDC_PREVIEW              1083
#define		IDC_CPU					1084
#define		IDS_PERMISSION			1085
#define		IDS_REMOTEPORT			1086
#define		IDS_SMTP				1087
#define		IDC_EXPBTN             1088
#define		IDC_IMPBTN             1089
#define		IDC_USERNAME            1090
#define		IDC_PASSWORD            1091
#define		IDC_PERMISSION			 1092

//103-02-21//
#define		IDS_PATH_REPEAT			10410
#define		IDS_ATM							10411
#define		IDS_TOTAL_STREAM		10412
#define		IDS_STREAM_URL			10413
#define		IDS_VIDEO_FORMAT		10414
#define		IDS_DEVICE_TREE			10415
#define		IDS_LAYOUT_TREE			10416
#define		IDS_PTZ_ENABLE			10417

//103-03-24//   In Playback rc.2
//MENU:IDR_MENU_VIDEO_SET//
//#define IDC_SET_VIDEOSET_FLIP						11000				IDS_SET_VIDEOSET_FLIP
//#define IDC_SET_VIDEOSET_UPDISEDOWN   11001				IDS_SET_VIDEOSET_UPDISEDOWN
//#define IDC_SET_FIX_RATIO									11002				IDS_SET_FIX_RATIO
//#define ID_MENU_SNAPSHOT							11003				IDS_SNAPSHOT
//#define IDM_MENU_OSD										11004				IDS_OSD
#define IDS_MENU_VIDEO_SET_REMOVE			11005

//MENU:IDR_MENU_REFRESH
#define IDS_MENUREFRESH_REFRESH				11006
#define IDS_MENUREFRESH_SDCARD				11007

//MENU:IDR_MENU_TIME_RESOLUTION
#define	IDS_TIMERESOLUTION_SECOND		11008
#define	IDS_TIMERESOLUTION_MINUTE		11009
#define	IDS_TIMERESOLUTION_HOUR			11010

//MENU:IDR_POPUP_EXPORT
#define IDS_EXPORTFILE_MARKIN					11011
#define IDS_EXPORTFILE_MARKOUT				11012
#define IDS_EXPORTFILE_EXPORT						11013

#define IDS_STATIC_BANK									11014
#define IDS_STATIC_ACCOUNT							11015
#define IDS_STATIC_FROM									11016

#define IDS_STATIC_MARKIN								11017
#define IDS_STATIC_MARKOUT							11018
#define IDS_STATIC_SPEED									11019
#define IDS_STATIC_UINT									11020

//SliderEvent
#define IDS_MSG_NO_CLIP_SELECTED				11021
#define IDS_MSG_NO_EVENT_SELECTED		11022
#define IDS_STATIC_EVENT_SN							11023
#define IDS_STATIC_NO_EVENT							11024

//vInitGridParam:TIMEGRID
#define	IDS_TIMEGRID_SECOND						11025
#define	IDS_TIMEGRID_MINUTE						11026
#define	IDS_TIMEGRID_HOUR							11027

#define IDS_MSG_NO_CAMERADATA				11028
#define IDS_STATIC_MARKEXPORT					11029


//Burn CD//
#define IDS_MSG_MARKIN_BIG							11121
#define IDS_MSG_MARK_DURATION_OVER	11122
#define IDS_BURNCD_DIALOG							11123
#define IDS_STATIC_GP_EXP								11124
#define IDS_STATIC_GP_BURN							11125
#define IDS_STATIC_ESTIME								11126
#define IDS_PROGRESS_TEXT								11127
#define IDS_STATIC_TLTIME								11128
#define IDS_BUFFER_TEXT									11129
#define IDS_BURN_RETRY									11130
#define IDS_MSG_EXPORT_NO_FILE					11131
#define IDS_MSG_EXPORT_TO_BURN				11132
#define IDS_BURN_BUTTON								11133
#define IDS_STATIC_GP_ADD_LIST					11134
#define IDS_STATIC_GP_DEVICE						11135
#define IDS_ADD_FILES_BUTTON						11136
#define IDS_ADD_FOLDER_BUTTON					11137
#define IDS_REMOVE_FILES_BUTTON				11138
#define IDS_STATIC_LABEL									11139
#define IDS_CLOSE_MEDIA_CHK						11140
#define IDS_EJECT_WHEN_FINISHED				11141
#define IDS_STATIC_SUPPORT_TYPES				11142
#define IDS_STATIC_SELECTED_MEDIA_TYPE	11143
#define IDS_MSG_BURN_COMPLETED				11144
#define IDS_MSG_VALIDATING							11145
#define IDS_MSG_FORMATTING						11146
#define IDS_MSG_INIT_HARDWARE					11147
#define IDS_MSG_OPTIMIZING_LASER			11148
#define IDS_MSG_FINALIZING							11149
#define IDS_MSG_COMPLETED							11150
#define IDS_MSG_NO_BURN_DEVICE				11151

//EtroCenter 103-05-16//
#define IDS_MSG_RESTART_REMOTESVR		11200

