/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */
#define ENABLE_NLS 1
/* #undef HAVE_CATGETS */
#define HAVE_GETTEXT 1
#define GETTEXT_PACKAGE "kino"
#define HAVE_LC_MESSAGES 1
/* #undef HAVE_STPCPY */
/* #undef HAVE_LIBSM */

/* always defined to indicate that i18n is enabled */
#define ENABLE_NLS 1

/* "" */
#define GETTEXT_PACKAGE "kino"

/* Define to 1 if you have the `bind_textdomain_codeset' function. */
#define HAVE_BIND_TEXTDOMAIN_CODESET 1

/* Define to 1 if you have the `dcgettext' function. */
#define HAVE_DCGETTEXT 1

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the `dirname' function. */
#define HAVE_DIRNAME 1

/* Wheter or not execinfo.h is present */
#define HAVE_EXECINFO_H 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Define to 1 if you have version 2.4 or greater of GTK+. */
#define HAVE_GTK24 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define if your <locale.h> file defines LC_MESSAGES. */
#define HAVE_LC_MESSAGES 1

/* Define to 1 if you have the `a52' library (-la52). */
/* #undef HAVE_LIBA52 */

/* Define to 1 if you have the `avc1394' library (-lavc1394). */
#define HAVE_LIBAVC1394 1

/* Define to 1 if you have libavcodec. */
/* #undef HAVE_LIBAVCODEC */

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `dv' library (-ldv). */
#define HAVE_LIBDV 1

/* Define to 1 if you have the <libgen.h> header file. */
#define HAVE_LIBGEN_H 1

/* Define to 1 if you have the `jpeg' library (-ljpeg). */
/* #undef HAVE_LIBJPEG */
#define HAVE_LIBJPEG 1

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `mpeg3' library (-lmpeg3). */
/* #undef HAVE_LIBMPEG3 */

/* Define to 1 if you have the `ogg' library (-logg). */
/* #undef HAVE_LIBOGG */

/* Define to 1 if you have the `png' library (-lpng). */
/* #undef HAVE_LIBPNG */

/* Define to 1 if you have the `pthread' library (-lpthread). */
#define HAVE_LIBPTHREAD 1

/* Define to 1 if you have the `quicktime' library (-lquicktime). */
/* #undef HAVE_LIBQUICKTIME */

/* Define to 1 if you have the `raw1394' library (-lraw1394). */
#define HAVE_LIBRAW1394 1

/* Define to 1 if you have the <libraw1394/raw1394.h> header file. */
#define HAVE_LIBRAW1394_RAW1394_H 1

/* Define to 1 if you have the `rom1394' library (-lrom1394). */
#define HAVE_LIBROM1394 1

/* Define to 1 if you have X11 shared memory extension. */
/* #undef HAVE_LIBSM */

/* Define to 1 if you have the `vorbis' library (-lvorbis). */
/* #undef HAVE_LIBVORBIS */

/* Define to 1 if you have the `vorbisenc' library (-lvorbisenc). */
/* #undef HAVE_LIBVORBISENC */

/* Define to 1 if you have the `Xext' library (-lXext). */
#define HAVE_LIBXEXT 1

/* Define to 1 if you have the `xml2' library (-lxml2). */
#define HAVE_LIBXML2 1

/* Define to 1 if you have the `Xv' library (-lXv). */
#define HAVE_LIBXV 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `opendir' function. */
#define HAVE_OPENDIR 1

/* Define to 1 if you have the <quicktime/lqt.h> header file. */
/* #undef HAVE_QUICKTIME_LQT_H */

/* Define to 1 if you have the <quicktime/quicktime.h> header file. */
/* #undef HAVE_QUICKTIME_QUICKTIME_H */

/* Define to 1 if you have the `realpath' function. */
#define HAVE_REALPATH 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
//#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/ipc.h> header file. */
#define HAVE_SYS_IPC_H 1

/* Define to 1 if you have the <sys/shm.h> header file. */
#define HAVE_SYS_SHM_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <X11/extensions/XShm.h> header file. */
#define HAVE_X11_EXTENSIONS_XSHM_H 1

/* Define to 1 if you have the <X11/extensions/Xvlib.h> header file. */
#define HAVE_X11_EXTENSIONS_XVLIB_H 1

/* Define to 1 if you have the <X11/Xlib.h> header file. */
#define HAVE_X11_XLIB_H 1

/* Define to 1 if you have the <X11/Xutil.h> header file. */
#define HAVE_X11_XUTIL_H 1

/* Define to 1 if you have an old version 0.8 of libraw1394. */
/* #undef LIBRAW1394_OLD */

/* Name of package */
#define PACKAGE "kino"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://jira.schirmacher.de/jira-kino/"

/* Define to the full name of this package. */
#define PACKAGE_NAME "kino"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "kino 0.7.6"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "kino"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.7.6"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.7.6"

/* Define to 1 if you have libdv (required). */
#define WITH_LIBDV 1

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Number of bits in a file offset, on hosts where this is settable. */
#define _FILE_OFFSET_BITS 64

/* Define to enable GNU extensions of glibc, notably large file support */
#define _GNU_SOURCE 1

/* Define for large files, on AIX-style hosts. */
/* #undef _LARGE_FILES */

/* Define to 1 for multi-threading. */
#define _REENTRANT 1
